[package]
name = "fluzo-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
fluzo-core.workspace = true
toml_edit.workspace = true
serde_json = { version = "=1.0.151", default-features = false, features = ["std"] }
hyper = { version = "=1.11.1", default-features = false, features = ["http1", "client"] }
hyper-util = { version = "=0.1.20", default-features = false, features = ["tokio"] }
http-body-util = { version = "=0.1.5", default-features = false }
tokio = { version = "=1.53.1", default-features = false, features = ["rt", "net", "time", "sync", "macros", "io-util"] }

[dev-dependencies]
serde.workspace = true
serde_json = { version = "=1.0.151", default-features = false, features = ["std"] }
hyper = { version = "=1.11.1", default-features = false, features = ["http1", "server", "client"] }
hyper-util = { version = "=0.1.20", default-features = false, features = ["tokio"] }
http-body-util = { version = "=0.1.5", default-features = false }
tokio = { version = "=1.53.1", default-features = false, features = ["rt", "net", "time", "sync", "macros", "io-util"] }
